debug: true
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:sqlserver://officeBookingServer.database.windows.net:1433;database=officeBookingDB;
    username: ${AZURE_DB_USERNAME}
    password: ${AZURE_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  data:
    jdbc:
      dialect: sql_server
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
